# Generated by Django 4.0.2 on 2022-03-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0002_rename_user_stats_user_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='questions_attempted',
            field=models.IntegerField(default=0),
        ),
    ]
