# Generated by Django 4.0.2 on 2022-03-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0006_stats_cat10_attempted_stats_cat10_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='cat11_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='cat11_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='cat12_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='cat12_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='cat14_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='cat14_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='cat15_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='cat15_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='cat17_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='cat17_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='cat21_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='cat21_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='cat22_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='cat22_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='cat23_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='cat23_correct',
            field=models.IntegerField(default=0),
        ),
    ]
